[package]
name = "chesscrunch-utils"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "port_finder"
path = "src/port_finder.rs"

[[bin]]
name = "health_monitor"
path = "src/health_monitor.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sys-info = "0.9"
