services:
  - type: web
    name: chessroyale
    env: node
    buildCommand: yarn install && yarn workspace @chessroyale/client add -D @tailwindcss/postcss postcss postcss-import tailwindcss autoprefixer && yarn build
    startCommand: yarn workspace server start
    envVars:
      - key: NODE_VERSION
        value: 18
