services:
  - type: web
    name: chessroyale
    env: node
    buildCommand: |
      rm -f package-lock.json
      yarn cache clean
      yarn install --frozen-lockfile
      yarn build
    startCommand: yarn workspace @chessroyale/server start
