services:
  - type: web
    name: chessroyale
    env: node
    buildCommand: |
      npm install -g vite
      yarn install
      yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18

databases:
  - name: chessroyale_db
    databaseName: chessroyale
    user: chessroyale_user
    plan: free
