services:
  - type: web
    name: chessroyale
    env: static
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: SESSION_SECRET
        fromSecret: your-session-secret
