services:
  - type: web
    name: chessroyale
    env: node
    plan: standard
    buildCommand: |
      # Install dependencies in the root directory
      yarn install
      # Install dependencies in the client directory
      cd client
      yarn install
      cd ..
      # Install dependencies in the server directory
      cd server
      yarn install
      cd ..
      # Install dependencies in the shared directory
      cd shared
      yarn install
      cd ..
      # Install additional type declarations
      yarn add -D @types/express-rate-limit
      yarn add -D @types/vite
      yarn add -D @types/node
      # Build the project
      yarn run build
    startCommand: yarn start
