services:
  - type: web
    name: chessroyale
    env: node
    buildCommand: yarn install --frozen-lockfile && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
