services:
  - type: web
    name: chessroyale
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: chessroyale_db
    databaseName: chessroyale
    user: chessroyale_user
    plan: free
