services:
  - type: web
    name: chessroyale
    env: node
    buildCommand: |
      yarn install
      yarn workspace @chessroyale/shared build
      yarn workspace @chessroyale/server build
      yarn workspace @chessroyale/client build
    startCommand: yarn workspace @chessroyale/server start
    envVars:
      - key: NODE_VERSION
        value: 18
