services:
  - type: web
    name: chessroyale
    env: node
    buildCommand: |
      chmod +x setup.sh
      ./setup.sh
    startCommand: yarn workspace @chessroyale/server start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3000
